name: Publish Website to Cpanel
On:
  push:
     branches:
       - main
  jobs: 
    FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
       - uses : action/checkout@2.1.0
         with: 
            fetch-depth: 2
       - name :  FTP-Deploy-Action
         user : lakindumalaka/FTP-Deploy-Action@3.1.1
         with:
          ftp-server: S{{secrets.FTP_SERVER}}
          ftp-username: ${{secrets.FTP_USERNAME}}
          ftp-password: ${{secrets.FTP_PASSWORD}}
